### ISSUE TITLE
PrivateGameRecord

### ISSUE THREAD

**Issue by pengneal** [MuMuloveU/wanghu#2]
请问下 这个表里面的二进制  如何解析？
老的版本里面没看到这个表，网上搜索好像是 火云洞红孩儿 增加的表上去，共三张表，
有2张里面有 二进制（16进制？）。

**Comment by smallsun123** [comment]
> 请问下 这个表里面的二进制 如何解析？
> 老的版本里面没看到这个表，网上搜索好像是 火云洞红孩儿 增加的表上去，共三张表，
> 有2张里面有 二进制（16进制？）。

你好，方便加我qq:1196455388吗？
